services:
  api:
    image: ${DOCKER_HUB_REPO}:latest
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      - redis
      - db
    command: ["python", "run.py"]
  worker:
    image: ${DOCKER_HUB_REPO}:latest
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      - redis
      - db
    command: ["python", "-m", "worker"]
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

