name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: shakira
          POSTGRES_PASSWORD: password
          POSTGRES_DB: documentreader_test
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U shakira -d documentreader_test"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download NLTK data
        run: |
          python -m nltk.downloader vader_lexicon

      - name: Check for Data Engineer.pdf
        run: |
          if [ ! -f test_uploads/Data\ Engineer.pdf ]; then
            echo "Error: Data Engineer.pdf not found in test_uploads. Please commit the file to the repository."
            exit 1
          fi

      - name: Verify PostgreSQL connection
        env:
          POSTGRES_USER: shakira
          POSTGRES_PASSWORD: password
          POSTGRES_DB: documentreader_test
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5433
          PGPASSWORD: password
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB -c "SELECT 1;"

      - name: Verify Redis connection
        run: |
          pip install redis
          python -c "import redis; r = redis.Redis(host='localhost', port=6379, db=1); r.ping()"

      - name: Run tests
        env:
          FLASK_ENV: testing
          POSTGRES_USER: shakira
          POSTGRES_PASSWORD: password
          POSTGRES_DB: documentreader_test
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5433
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          REDIS_DB: 1
        run: python -m unittest discover -s tests -v