name: Run Tests for DocumentReader

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      db:
        image: postgres:13
        env:
          POSTGRES_USER: shakira
          POSTGRES_PASSWORD: password
          POSTGRES_DB: documentreader_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U shakira -d documentreader_test"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          FLASK_ENV: testing
          POSTGRES_USER: shakira
          POSTGRES_PASSWORD: password
          POSTGRES_DB: documentreader_test
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          REDIS_DB: 1
        run: |
          pytest tests/test_app.py -v